locals {
  location            = "japaneast"
  resource_group_name = "example-resources"
  vnet_name           = "example-network"
  public_subnet_name  = "subnet1"
  private_subnet_name = "subnet2"
  nic_private_name    = "example-private-nic"
  nic_public_name     = "example-public-nic"
  nsg_public_name     = "example-public-nsg"
  nsg_private_name    = "example-private-nsg"
  vm_name             = "example-machine"
  admin_username      = "satake"
  admin_password      = "satake007!"
  public_ip           = "myPublicIP"
  vm_extension_hostname="hostname_extension"
  testname="testname"
}